CREATE TABLE IF NOT EXISTS BOOK_ENTITY (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publication_year VARCHAR(4) NOT NULL,
    pages INTEGER NOT NULL
);
